@echo off
echo Starting Recipe Haven Development Server...
echo.
echo Installing dependencies...
call npm install
echo.
echo Building React app...
call npm run build
echo.
echo Starting server...
call npm start
pause